This creates the hopepage outline of Mobile Portfolio view
steveWDamesJr/Portfolio pull request #1
Opened 2021-11-25 03:42 UTC by steveWDamesJr

Add files:

index.html
.gitignore
CSS/app.css
HTML/CSS linters.yml
Update README
Add Images for Mobile view of Portfolio homepage
Add toolbar
Add Hero Section description and styling

2021-11-25 12:08 UTC, rotimiazeez requested changes
# Hi @steveWDamesJr 👋, 
![](https://media.giphy.com/media/3orieSeDRFY491jKwM/giphy.gif)
## Good job so far!👏👏
### To Highlight!🔥🔥
- No linter error ✔
- Good commit messages👏
- Good PR description👌
- Good Readme👍
### There are some issues that you still need to work on to go to the next project but you are almost there!🚀
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 12:08 UTC, rotimiazeez commented on index.html
> +  </section>
- [ ] Kindly make sure the design matches the template of your choice.
- Your design

![your design](https://user-images.githubusercontent.com/44624138/143438133-cd4ac6c1-8dd3-4a01-9658-7f929d2ed576.png)
- Figma design
![figma](https://user-images.githubusercontent.com/44624138/143438199-5e103db6-3f0c-4a25-85a4-5d139c702cb3.png)

2021-11-25 16:00 UTC, steveWDamesJr commented on index.html
> +    <img src="/IMAGES_MOBILE/ham_menu.svg" alt="menu">
Hello, thank you so much for your review and advice!

Could you clarify why the **image** at line "21" appears **broken**? In the screen below (using both browsers Firefox Developer edition, and Google Chrome), the **svg image** [hamburger menu] is visible at the top right hand side of the screen.

To improve UX I could make the img a link so that default coding such as **hand selector** on hover are visible.

<img width="956" alt="Screen Shot 2021-11-25 at 10 42 49 AM" src="https://user-images.githubusercontent.com/81635839/143471537-1bf9b44e-160f-458e-b2b9-4f9bb3740548.png">


Thank you in advance for your clarification and have a great day!

2021-11-27 09:36 UTC, steveWDamesJr commented on index.html
> +  </nav>
Thank you. This section now matches Poppins font and #6070ff color from template.

<img width="1346" alt="Screen Shot 2021-11-27 at 4 27 57 AM" src="https://user-images.githubusercontent.com/81635839/143675960-06c010a9-5532-4b14-891f-bc7da19acf40.png">

2021-11-27 09:40 UTC, steveWDamesJr commented on index.html
> +    <img src="/IMAGES_MOBILE/ham_menu.svg" alt="menu">
I have changed the image svg to a div created menu bar.

2021-11-27 11:05 UTC, keneogu requested changes
Hi @steveWDamesJr, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] Please check your design, the background image doesn't display.
Your design
![vin](https://user-images.githubusercontent.com/53356820/143678721-c098eff1-d59e-48fb-a3f5-f663a7c60d87.png)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------

2021-11-27 19:35 UTC, Rustamxon7 approved these changes
## Hi @steveWDamesJr   👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![aproved office](https://user-images.githubusercontent.com/69011963/143719952-e3268ce9-b482-46b0-a916-d6106d7bb3e4.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-11-27 19:51 UTC, merged